VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('02')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('58')
MAJOR_VERSION = 1
MINOR_VERSION = 8
PATCH_VERSION = 202401021158
version_date = '2024/01/02 11:58'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
