VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('19')
VERSION_HOUR = int('23')
VERSION_MINUTE = int('41')
MAJOR_VERSION = 0
MINOR_VERSION = 13
PATCH_VERSION = 202301192341
version_date = '2023/01/19 23:41'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
