VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('29')
VERSION_HOUR = int('21')
VERSION_MINUTE = int('34')
MAJOR_VERSION = 0
MINOR_VERSION = 12
PATCH_VERSION = 202212292134
version_date = '2022/12/29 21:34'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
